FROM ubuntu

ENV WORKDIR /root/web/

RUN apt-get update && apt-get install -y python3 python3-pip git npm

WORKDIR  $WORKDIR

git clone https://github.com/YashMarmat/FullStack_Ecommerce_App.git

cd FullStack_Ecommerce_App

 --break-system-packages
pyproject.toml-based

sudo apt-get install libjpeg-dev zlib1g-dev

EXPOSE 4000